version: 2.1
jobs:
  eslint:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run: yarn install
      - run: yarn eslint
  stylelint:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run: yarn install
      - run: yarn stylelint
workflows:
  build-deploy:
    jobs:
      - eslint
      - stylelint